Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "2"
    vb.memory = "2048"
    # nested virtulizationの有効化
    vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
  end

  config.vm.box = "bento/ubuntu-20.04"
  config.vm.synced_folder "./data", "/home/vagrant/data"

  config.vm.network "forwarded_port", guest: 3003, host: 3003
  config.vm.provision "shell", path: 'bootstrap.sh', privileged: false
end
